# Generated by Django 2.2.1 on 2019-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190703_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '文章类型', 'verbose_name_plural': '文章类型'},
        ),
    ]
