# Generated by Django 2.2.1 on 2019-06-28 10:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20190625_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
