# Generated by Django 2.2.1 on 2019-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20190628_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_time'], 'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
    ]
