# Generated by Django 2.2.1 on 2019-07-02 19:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20190703_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_deleted',
            field=models.NullBooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='image',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
