# Generated by Django 2.0.7 on 2019-06-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0001_initial'),
        ('user_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comment_time'],
            },
        ),
        migrations.RemoveField(
            model_name='homemessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='HomeMessage',
        ),
    ]
