# Generated by Django 2.0.7 on 2019-06-25 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0002_auto_20190623_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
