# Generated by Django 2.2.1 on 2019-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0003_auto_20190625_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-comment_time'], 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='imagecomment',
            options={'ordering': ['-comment_time'], 'verbose_name': '图片评论', 'verbose_name_plural': '图片评论'},
        ),
    ]
