# Generated by Django 2.2.1 on 2019-07-02 19:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0004_auto_20190703_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', verbose_name='文章对象'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='image',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='图片对象'),
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
    ]
